apiVersion: v1
kind: Service
metadata:
  name: komugi-back-service
spec:
  type: NodePort
  selector:
    end: komugi-back
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32228
